name: Check code formatting

on:
  push:
    paths:
      - '**/*.js'
      - '.github/**/*.yml'
      - '.eslintrc.json'
      - '.prettierrc'
      - 'package-lock.json'
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    name: Run prettier & eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'

      - name: Cache NPM dependencies
        id: npm-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run configured Prettier & ESLint
        run: npm run lint
